306 : Product Catalogue
OpenSRP/opensrp-server-core pull request #313
Opened 2020-09-01 16:11 UTC by rehammuzzamil

https://github.com/OpenSRP/opensrp-server-core/issues/306

2020-10-07 05:34 UTC, rehammuzzamil commented
There is an issue with the **PUT** end-point. As per the business, the image can also be updated in an edit-mode. Therefore, we need to provide support for the update of both JSON payload and Multipart file in an edit. To make it work, I tried with **@RequestPart** but it did not work. The problem is PUT request represents a single resource. But multi parts means multiple resources in a single body. Therefore, it throws an exception ` Unable to process parts as no multi-part configuration has been provided.`
The solution could be to implement a customized **MultipartResolver** class and override the existing default multipart resolver in an XML configuration to allow a multipart request for both POST and PUT end-point.
Please provide your feedback @dubdabasoduba. Thanks!

2020-10-09 06:35 UTC, dubdabasoduba requested changes

2020-10-09 06:35 UTC, dubdabasoduba commented on src/main/java/org/opensrp/repository/postgres/ProductCatalogueRepositoryImpl.java
> +		//		int rowsAffected = customProductCatalogueMapper.deleteByExample(productCatalogueExample);
Please remove this unused piece of code

2020-10-09 07:59 UTC, dubdabasoduba commented
> There is an issue with the **PUT** end-point. As per the business, the image can also be updated in an edit-mode. Therefore, we need to provide support for the update of both JSON payload and Multipart file in an edit. To make it work, I tried with **@RequestPart** but it did not work. The problem is PUT request represents a single resource. But multi parts means multiple resources in a single body. Therefore, it throws an exception ` Unable to process parts as no multi-part configuration has been provided.`
> The solution could be to implement a customized **MultipartResolver** class and override the existing default multipart resolver in an XML configuration to allow a multipart request for both POST and PUT end-point.
> Please provide your feedback @dubdabasoduba. Thanks!

@rehammuzzamil I agree. I also found the same method after doing some research. So let's work with this solution.

2020-10-09 13:46 UTC, rehammuzzamil commented on src/main/java/org/opensrp/repository/postgres/ProductCatalogueRepositoryImpl.java
> +		//		int rowsAffected = customProductCatalogueMapper.deleteByExample(productCatalogueExample);
Done

2020-10-16 07:04 UTC, dubdabasoduba approved these changes

2020-10-16 12:08 UTC, rehammuzzamil commented
As discussed with @dubdabasoduba , closing this PR.

2020-10-16 12:08 UTC, closed without merging